//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingID { get; set; }
        public Nullable<int> FlightID { get; set; }
        public Nullable<int> pID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
    
        public virtual Flights Flights { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
